### PR TITLE
Removed dead link of snowflake ODBC driver and added new working link.

### PR DESCRIPTION
**Pull request by hrkachhia**
Removed dead link of snowflake ODBC driver and added new working link. As well as I have also added snowsql_role environment variable .

### CODE REVIEW

**Comment by hrkachhia** [comment]
Can you please review the pull request provide your valuable feedback?

**Comment by theory** [comment]
I am on vacation and will review when I return

**Comment by hrkachhia** [comment]
> I am on vacation and will review when I return

Can you please review it? if you return from the vacation.

**Comment by theory** [comment]
Sorry, overlooked this when I got back. Done in c6b5a92. Thanks for switching to the x8664 build of the ODBC driver, I had somehow missed that when it appeared.

**Pull request closed without merging**
