### PR TITLE
i want to setup snowflake

### PR DESCRIPTION
**Pull request by rubenslj00**
please

### CODE REVIEW

**Comment by rubenslj00** [comment]
THE JOB IS FAIL

**Review by rubenslj00 — COMMENTED** [review]
CHECK

**Comment by rubenslj00** [comment]
BUILD

**Comment by theory** [comment]
This would be difficult to test (unless there's a service like TravisCI for Jenkins?) and somewhat specific to your environment. I have a similar need at work, but the `Jenkinsfile` I wrote lives in an Internal repo that's integrated to our Jenkins cluster, and it pulls from the upstream to do the build. No need to I integrate it here.

**Comment by rubenslj00** [comment]
Thank you for your feedback,  can I see structure of your Jenkinsfile? If
possible

Thank you again

**Comment by theory** [comment]
```
pipeline {
    agent { label 'docker' }
    triggers { cron '@weekly' }
    stages {
        stage ('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    extensions: [[$class: 'CleanCheckout']],
                    userRemoteConfigs: [[url: 'https://github.com/sqitchers/docker-sqitch.git']]
                ])
            }
        }
        stage('Build') {
            environment {
                DIR = 'snowflake'
                REGISTRY = 'docker-registry.example.com/sqitch'
            }
            steps {
                sh './build --build-arg sf_account=example'
                sh "docker push ${env.REGISTRY}/sqitch"
            }
        }
    }
}

```

**Comment by rubenslj00** [comment]
Thank you very much!  David , now understand I have to configure the
Jenkinsfile with my docker registry , my snowflake account etc....

I have a deal for you , I don't know if it is a good idea , let's schedule
a call for 30mn just for talking and I'm ready to pay you 100 for 30 mmn 1
hour 200 , please. I just want a clear idea  because I want to implement
snowface in my environment.

Thank you so much David

**Comment by theory** [comment]
Oh I see how things are different. My `Jenkinsfile` builds the Sqitch docker image and pushes it to our internal Docker repository. You'll need to build Sqitch, too, though you don't have to use a repo if you don't have one. But I see now that the focus for your `Jenkinsfile` is actually deploying changes. We don't do that for prod databases, but do run unit tests for our database projects, so need to build a database. I can dig up an example of that tomorrow.

**Comment by rubenslj00** [comment]
Ok, I will so happy..

check this jenkinsfile , i'm still stuck in the deployment stages..

pipeline {
options {
timeout(time: 1, unit: 'HOURS')
}
agent{
docker {
image '983436/sqitch-snowflake:v1.0'
args "-u root -v /var/run/docker.sock:/var/run/docker.sock --entrypoint=''"
}
}
stages{
stage('Test sqitch installation'){
steps{
sh 'sqitch --version'
}
}
stage('Test snowsql installation'){
steps{
sh 'snowsql --version'
}
}
stage('Sqitch Deploy'){
steps {
withCredentials([usernamePassword(credentialsId: 'Sqitch', passwordVariable:
'PASSWORD', usernameVariable: 'USERNAME')]) {
sh ' cd ~/.snowsql && cat config'
sh 'sqitch deploy "db:snowflake://$USERNAME:$PASSWORD@fwa76732
/Sqitch_Jenkins?Driver=Snowflake;warehouse=compute_wh;"'
}
}
}
stage('Sqitch Verify'){
steps {
withCredentials([usernamePassword(credentialsId: 'Sqitch', passwordVariable:
'PASSWORD', usernameVariable: 'USERNAME')]) {
sh 'sqitch verify "db:snowflake://$USERNAME:$PASSWORD@fwa76732
/Sqitch_Jenkins?Driver=Snowflake;warehouse=compute_wh;"'
}
}
}
stage('Sqitch Status'){
steps {
withCredentials([usernamePassword(credentialsId: 'Sqitch', passwordVariable:
'PASSWORD', usernameVariable: 'USERNAME')]) {
sh 'sqitch status "db:snowflake://$USERNAME:$PASSWORD@fwa76732
/Sqitch_Jenkins?Driver=Snowflake;warehouse=compute_wh;"'
}
}
}
}
}

**Comment by theory** [comment]
Sorry I never got round to looking or a Jenkinsfile example of building a Snowflake database, and now I'm no longer with that employer. If you still need help and want to try again, please post to the [sqitch mail list](https://groups.google.com/group/sqitch-users), rather than submit a pull request, since we are unlikely to merge a Jenkinsfile into our project.

**Pull request closed without merging**
